#!/bin/sh
INSTALLDIR=/usr/share/xtrkcad

LOGF=/tmp/xtrkcad-setup.log
if [ -f "${LOGF}" ] ; then
	chmod 666 ${LOGF}
else
	LOGF=/dev/null
fi

( su -p -c "sh ${INSTALLDIR}/xtrkcad-setup remove ${INSTALLDIR}" $SUDO_USER ) >> ${LOGF} 2>&1

exit 0

