/*
 * DO NOT EDIT! This file has been automatically created by genhelp.
 * Changes to this file will be overwritten. Edit this: genhelp.json
 */
#include <stdio.h>
#include "wlib.h"

wBalloonHelp_t balloonHelp[] = {
	{ "Close", N_("Closes the dialog") },
	{ "Help", N_("Invokes online help for this dialog") },
	{ "about", N_("No Help") },
	{ "about-about", N_("No Help") },
	{ "about-ok", "" },
	{ "addElev-value", N_("Raise or Lower all Selected Track") },
	{ "block-name", N_("Name of block") },
	{ "block-script", N_("Script that the block will run") },
	{ "block-segments", N_("List of tracks in the Block") },
	{ "cancel", N_("Cancels this command") },
	{ "carinv-add", N_("Add a new Car Item") },
	{ "carinv-delete", N_("Delete from Inventory or return to Shelf") },
	{ "carinv-edit", N_("Edit the selected Car Item") },
	{ "carinv-export", N_("Export a Car Item .csv file") },
	{ "carinv-import", N_("Import a Car Item .csv file") },
	{ "carinv-list", "" },
	{ "carinv-ok", N_("Finds the selected Car Item on the layout") },
	{ "carinv-savetext", N_("Create a text list of the Car Items") },
	{ "carinv-sort1", N_("Sort the Item list") },
	{ "carinv-sort2", N_("Sort the Item list") },
	{ "carinv-sort3", N_("Sort the Item list") },
	{ "carinv-sort4", N_("Sort the Item list") },
	{ "carpart-bodyColor", N_("Car body Color") },
	{ "carpart-canvas", N_("Diagram of Car") },
	{ "carpart-carLength", N_("Length of car body") },
	{ "carpart-carWidth", N_("Width of car body") },
	{ "carpart-condition", N_("Condition of car") },
	{ "carpart-cpldLen", N_("Overall Coupled Length") },
	{ "carpart-cplrLen", N_("Coupler Length from end of car") },
	{ "carpart-cplrMount", N_("Coupler are mounted on body or truck") },
	{ "carpart-currPrice", N_("Current Price") },
	{ "carpart-desc", N_("Optional description of the Car Part") },
	{ "carpart-dispmode", N_("Display Car Item information or reporting marks and dimensions") },
	{ "carpart-flip", N_("Flip car image") },
	{ "carpart-import", N_("Use the Selected figure as the car image") },
	{ "carpart-index", N_("Item Index Number") },
	{ "carpart-isLoco", N_("Is the Car a Locomotive?") },
	{ "carpart-manuf", N_("Manufacturer name") },
	{ "carpart-multinum", N_("Do all the cars have the same Number?") },
	{ "carpart-new", N_("Create a new car Part or Prototype definitions") },
	{ "carpart-new-menu", N_("Create a new car Part or Prototype definitions") },
	{ "carpart-notes", N_("Notes about the car") },
	{ "carpart-number", N_("Car Number") },
	{ "carpart-ok", N_("Add or Update car object") },
	{ "carpart-partno", N_("Manufacturer Part Number") },
	{ "carpart-partno-list", N_("Part Number and Description") },
	{ "carpart-protokind-list", N_("Car Type") },
	{ "carpart-prototype", N_("Car Prototype") },
	{ "carpart-prototype-list", N_("Car Prototype") },
	{ "carpart-purchDate", N_("Original Purchase Date - yyyymmdd") },
	{ "carpart-purchPrice", N_("Original Purchase Price") },
	{ "carpart-quantity", N_("Number of identical cars to be entered") },
	{ "carpart-repmark", N_("Reporting Marks (Roadname abbreviation)") },
	{ "carpart-reset", N_("Use the default figure as the car image") },
	{ "carpart-road", N_("Full Roadname") },
	{ "carpart-serviceDate", N_("Last Service Date - yyyymmdd") },
	{ "carpart-trkCenter", N_("Distance between Trucks ") },
	{ "carpart-trkCenterOffset", N_("Distance Trucks are displaced along Car") },
	{ "carpart-type", N_("Car Type") },
	{ "circle-radius", N_("Specifies the radius of the circle track") },
	{ "cmdAbout", N_("About program dialog") },
	{ "cmdAbove", N_("Move selected object to top") },
	{ "cmdAddElevations", N_("Raise or lower all selected tracks") },
	{ "cmdAngle", N_("Show a protractor") },
	{ "cmdBackgroundShow", N_("Show/Hide Background") },
	{ "cmdBelow", N_("Move selected object to bottom") },
	{ "cmdBezier", N_("Create Bezier track") },
	{ "cmdBlockCreate", N_("Create a section of track for automation") },
	{ "cmdBlockEdit", N_("Edit a block definition ") },
	{ "cmdBridge", N_("Make/Unmake a track a bridge") },
	{ "cmdCarDesc", N_("Create a new Car/Loco description") },
	{ "cmdCarInventory", N_("Manage your Car and Loco Inventory") },
	{ "cmdCircleCenter", N_("Create track circle from center") },
	{ "cmdCircleFixedRadius", N_("Create fixed radius track circle") },
	{ "cmdCircleSetCmd", N_("Set Circle Track creation mode") },
	{ "cmdCircleTangent", N_("Create track circle from tangent") },
	{ "cmdClearElevations", N_("Removes elevation from Selected tracks") },
	{ "cmdClone", N_("Copy objects to clipboard and duplicate them in exactly the same place") },
	{ "cmdCmdopt", N_("Command Options dialog") },
	{ "cmdColor", N_("Controls colors") },
	{ "cmdConnect", N_("Connect two tracks") },
	{ "cmdContmgm", N_("Manage control elements") },
	{ "cmdControl", N_("Create a control for layout automation") },
	{ "cmdControlElements", N_("Select control element to create") },
	{ "cmdConvertFrom", N_("Convert from Cornu and Bezier to Fixed Track") },
	{ "cmdConvertSetCmd", N_("Set Convert mode") },
	{ "cmdConvertTo", N_("Convert from Fixed Track to Cornu") },
	{ "cmdCopy", N_("Copy selected objects to clipboard") },
	{ "cmdCornu", N_("Create Cornu track") },
	{ "cmdCurveCenter", N_("Create curved track from center") },
	{ "cmdCurveChord", N_("Create curved track from chord") },
	{ "cmdCurveEndPt", N_("Create curved track from end-point") },
	{ "cmdCurveSetCmd", N_("Set Curve Track creation mode") },
	{ "cmdCurveTangent", N_("Create curved track from tangent") },
	{ "cmdCustmgm", N_("Manipulate Custom designer entries") },
	{ "cmdCut", N_("Moves selected objects to clipboard") },
	{ "cmdDebug", N_("No Help") },
	{ "cmdDelete", N_("Delete objects") },
	{ "cmdDemo", N_("Playback demos") },
	{ "cmdDescribe", N_("Change Object Properties") },
	{ "cmdDescribeMode", N_("Change to properties mode") },
	{ "cmdDeselectAll", N_("Deselect all selected objects") },
	{ "cmdDisplay", N_("Change Display parameters") },
	{ "cmdDrawBench", N_("Create benchwork") },
	{ "cmdDrawBezierCurve", N_("Create a Bezier line") },
	{ "cmdDrawBox", N_("Create a box") },
	{ "cmdDrawCircle", N_("Create a circle") },
	{ "cmdDrawCircleCenter", N_("Draw a circle line from center") },
	{ "cmdDrawCircleFixedRadius", N_("Draw a fixed radius circle line") },
	{ "cmdDrawCircleSetCmd", N_("Set Circle drawing command") },
	{ "cmdDrawCircleTangent", N_("Draw a circle line from tangent") },
	{ "cmdDrawCurve", N_("Create a curved line") },
	{ "cmdDrawCurveCenter", N_("Create a curved line from center") },
	{ "cmdDrawCurveChord", N_("Create a curved line from chord") },
	{ "cmdDrawCurveEndPt", N_("Create a curved line from End") },
	{ "cmdDrawCurveSetCmd", N_("Set Curve drawing command") },
	{ "cmdDrawCurveTangent", N_("Create a curved line from tangent") },
	{ "cmdDrawDimLine", N_("Create a dimension line") },
	{ "cmdDrawFilledBox", N_("Create a filled box") },
	{ "cmdDrawFilledCircleCenter", N_("Draw a filled circle from center") },
	{ "cmdDrawFilledCircleFixedRadius", N_("Draw a fixed radius filled circle") },
	{ "cmdDrawFilledCircleTangent", N_("Draw a filled circle from tangent") },
	{ "cmdDrawFilledCurve", N_("Create a filled circle") },
	{ "cmdDrawFilledPolygon", N_("Create a filled polygon") },
	{ "cmdDrawLine", N_("Create a straight line") },
	{ "cmdDrawLineSetCmd", N_("Set Line drawing command") },
	{ "cmdDrawPolygon", N_("Create a polygon") },
	{ "cmdDrawPolyline", N_("Create a polyline") },
	{ "cmdDrawShapeSetCmd", N_("Set Shape drawing command") },
	{ "cmdDrawTableEdge", N_("Draw table edge") },
	{ "cmdEasement", N_("Easement menu") },
	{ "cmdElevation", N_("Change Elevations") },
	{ "cmdEnumerate", N_("Generate a Parts List of selected objects") },
	{ "cmdExport", N_("Export an .xti file") },
	{ "cmdExportBmap", N_("Export a Bitmap image") },
	{ "cmdExportDXF", N_("Export a DXF file") },
	{ "cmdExportImportSetCmd", N_("Set Import/Export mode") },
	{ "cmdExportSVG", N_("Export an SVG file") },
	{ "cmdFileNote", N_("Document") },
	{ "cmdFlip", N_("Flip selected objects") },
	{ "cmdGrid", N_("Adjust snap grid") },
	{ "cmdGridEnable", N_("Enable snap grid") },
	{ "cmdGridShow", N_("Show snap grid") },
	{ "cmdGroup", N_("Create a structure from a Group of objects") },
	{ "cmdHandLaidTurnout", N_("Create a hand-laid turnout") },
	{ "cmdHelix", N_("Create a track helix") },
	{ "cmdImport", N_("Import an .xti file") },
	{ "cmdImportModule", N_("Import an .xti file as a Module") },
	{ "cmdJoinLine", N_("Join two lines or polylines") },
	{ "cmdJoinSetCmd", N_("Set Join mode") },
	{ "cmdJoinTrack", N_("Join two tracks") },
	{ "cmdLayer", N_("Change Layers") },
	{ "cmdLayerSet", N_("Selects the current drawing layer") },
	{ "cmdLayerShow0", N_("Layer") },
	{ "cmdLayerShow1", N_("Layer") },
	{ "cmdLayerShow10", N_("Layer") },
	{ "cmdLayerShow11", N_("Layer") },
	{ "cmdLayerShow12", N_("Layer") },
	{ "cmdLayerShow13", N_("Layer") },
	{ "cmdLayerShow14", N_("Layer") },
	{ "cmdLayerShow15", N_("Layer") },
	{ "cmdLayerShow16", N_("Layer") },
	{ "cmdLayerShow17", N_("Layer") },
	{ "cmdLayerShow18", N_("Layer") },
	{ "cmdLayerShow19", N_("Layer") },
	{ "cmdLayerShow2", N_("Layer") },
	{ "cmdLayerShow3", N_("Layer") },
	{ "cmdLayerShow4", N_("Layer") },
	{ "cmdLayerShow5", N_("Layer") },
	{ "cmdLayerShow6", N_("Layer") },
	{ "cmdLayerShow7", N_("Layer") },
	{ "cmdLayerShow8", N_("Layer") },
	{ "cmdLayerShow9", N_("Layer") },
	{ "cmdLayout", N_("Layout parameters") },
	{ "cmdLinkNote", N_("Weblink") },
	{ "cmdMagneticSnap", N_("Turn magnetic snap on or off") },
	{ "cmdMapShow", N_("Show/Hide Map Window") },
	{ "cmdMeasureSetCmd", N_("Select Measurement Tool") },
	{ "cmdModify", N_("Modify or extend a track") },
	{ "cmdModifyMode", N_("Change To modify mode") },
	{ "cmdMove", N_("Move selected objects") },
	{ "cmdMoveLabel", N_("Move a label") },
	{ "cmdMoveToCurrentLayer", N_("Move selected objects to current layer") },
	{ "cmdNote", N_("Place a note on the layout") },
	{ "cmdOutputbitmap", N_("Print a bitmap") },
	{ "cmdPan", N_("Pan or zoom the layout") },
	{ "cmdPanMode", N_("Change to zoom/pan mode") },
	{ "cmdParallelLine", N_("Create a parallel line") },
	{ "cmdParallelSetCmd", N_("Set Parallel mode") },
	{ "cmdParallelTrack", N_("Create a parallel track") },
	{ "cmdParameter", N_("Register") },
	{ "cmdPaste", N_("Copy objects from clipboard") },
	{ "cmdPref", N_("Perferences dialog") },
	{ "cmdPricelist", N_("Display prices of turnouts, sectional tracks and structures") },
	{ "cmdPrint", N_("Print the layout") },
	{ "cmdPrmfile", N_("Loads and unloads parameter files into/from toolbar") },
	{ "cmdProfile", N_("Elevation Profile Command") },
	{ "cmdProfileDraw", N_("Profile") },
	{ "cmdRecord", N_("Command recorder") },
	{ "cmdRedo", N_("Redo last undo") },
	{ "cmdRefreshCompound", N_("Update selected Turnout and Structure definitions") },
	{ "cmdRescale", N_("Rescale selected objects") },
	{ "cmdRotate", N_("Rotate selected object(s)") },
	{ "cmdRuler", N_("Show a ruler") },
	{ "cmdSelect", N_("Select objects") },
	{ "cmdSelectAll", N_("Selects all objects on the layout") },
	{ "cmdSelectCurrentLayer", N_("Selects all objects in the current Layer") },
	{ "cmdSelectIndex", N_("Choose objects by Index number") },
	{ "cmdSelectInvert", N_("Invert current selection") },
	{ "cmdSelectMode", N_("Change To Select Mode") },
	{ "cmdSelectOrphaned", N_("Select stranded (unconnected) track pieces") },
	{ "cmdSensor", N_("Create a sensor (ie. a occupancy detector or a toggle switch)") },
	{ "cmdSetup", N_("Configure the Printer") },
	{ "cmdSignal", N_("Create a signal for train control") },
	{ "cmdSplitDraw", N_("Split a straight, curved, circle, polygon or polyline Draw Object ") },
	{ "cmdSplitSetCmd", N_("Set Split mode") },
	{ "cmdSplitTrack", N_("Split a track") },
	{ "cmdSticky", N_("Choose which commands are sticky") },
	{ "cmdStraight", N_("Create straight track") },
	{ "cmdStructure", N_("Place a structure on the layout") },
	{ "cmdSwitchMotorCreate", N_("Create a switchmotor for turnout control") },
	{ "cmdSwitchMotorEdit", N_("Edit a switchmotor definition") },
	{ "cmdText", N_("Enter text on the layout") },
	{ "cmdTextNote", N_("Text Note") },
	{ "cmdTextSize", N_("Controls the size of the entered text") },
	{ "cmdTip", N_("Tip of the Day window") },
	{ "cmdTrain", N_("Run Trains") },
	{ "cmdTrainExit", N_("Exit Trains") },
	{ "cmdTrainMode", N_("Change To Run Trains Mode") },
	{ "cmdTrainNewCar", N_("Place a car on the layout") },
	{ "cmdTrainPause", N_("Pause/Resume Trains") },
	{ "cmdTrimDraw", N_("Trim a line, circle or polyline Draw Object using a second Object") },
	{ "cmdTunnel", N_("Hide/Unhide a track") },
	{ "cmdTurnout", N_("Place a turnout or sectional track") },
	{ "cmdTurnoutNew", N_("Create a new turnout definition") },
	{ "cmdTurntable", N_("Place a turntable") },
	{ "cmdUndo", N_("Undo last command") },
	{ "cmdUngroup", N_("Ungroup objects") },
	{ "cmdUpdatetitle", N_("Updates old source files with 3 part titles") },
	{ "cmdWidth0", N_("Draw tracks with thin lines") },
	{ "cmdWidth2", N_("Draw tracks with medium lines") },
	{ "cmdWidth3", N_("Draw tracks with thick lines") },
	{ "cmdZoom", N_("Change drawing scale") },
	{ "cmdZoomExtent", N_("Zoom to Fit") },
	{ "cmdZoomIn", N_("Zoom in") },
	{ "cmdZoomOut", N_("Zoom out") },
	{ "cmdopt-ok", "" },
	{ "cmdopt-preselect", N_("Default command is Describe or Select") },
	{ "cmdopt-rightclickmode", N_("Action to invoke on Right-Click") },
	{ "cmdopt-selectmode", N_("Replace current selection with clicked object or add clicked object to selection") },
	{ "cmdopt-selectzero", N_("Clicking into an empty area clears selection if select mode is <add>") },
	{ "contents-label", N_("Contents Label for new Parameter file") },
	{ "contmgm-delete", N_("Delete the element") },
	{ "contmgm-edit", N_("Edit the element") },
	{ "contmgm-inx", N_("The list of control elements") },
	{ "cornuMod", N_("Modify Cornu") },
	{ "cornuMod-endangle", N_("End Angle") },
	{ "cornuMod-endradius", N_("End Radius") },
	{ "curved-fixed-radius", N_("Desired curve radius for new track") },
	{ "curvefixed", N_("Curved Fixed") },
	{ "curvefixed-radius", N_("Preferred Radius") },
	{ "custmgm-delete", N_("Remove selected entries") },
	{ "custmgm-edit", N_("Change description, manufacturer or part number.") },
	{ "custmgm-export", N_("Copy selected entries to parameter file") },
	{ "custmgm-inx", N_("List of custom designed turnouts and structures") },
	{ "custmgm-newcar", N_("Create the selected type") },
	{ "custmgm-newtype", N_("Create a new part or prototype?") },
	{ "custmgm-ok", N_("Update custom file and close") },
	{ "debug-Curve", N_("No Help") },
	{ "debug-EndPt", N_("No Help") },
	{ "debug-Join", N_("No Help") },
	{ "debug-Print", N_("No Help") },
	{ "debug-ReadTracks", N_("No Help") },
	{ "debug-Structure", N_("No Help") },
	{ "debug-Track", N_("No Help") },
	{ "debug-Turnout", N_("No Help") },
	{ "debug-ok", "" },
	{ "demo-next", N_("Skip to next demo") },
	{ "demo-quit", N_("Stops the demonstration and returns you to XTrackCAD") },
	{ "demo-speed", N_("Select speed of Playback") },
	{ "demo-step", N_("Executes the next step of the demo") },
	{ "demo-text", N_("This is where comments about the demo are displayed") },
	{ "describe-C1", "" },
	{ "describe-F1", "" },
	{ "describe-F10", "" },
	{ "describe-F11", "" },
	{ "describe-F12", "" },
	{ "describe-F13", "" },
	{ "describe-F14", "" },
	{ "describe-F15", "" },
	{ "describe-F16", "" },
	{ "describe-F17", "" },
	{ "describe-F18", "" },
	{ "describe-F19", "" },
	{ "describe-F2", "" },
	{ "describe-F20", "" },
	{ "describe-F3", "" },
	{ "describe-F4", "" },
	{ "describe-F5", "" },
	{ "describe-F6", "" },
	{ "describe-F7", "" },
	{ "describe-F8", "" },
	{ "describe-F9", "" },
	{ "describe-I1", "" },
	{ "describe-I2", "" },
	{ "describe-I3", "" },
	{ "describe-I4", "" },
	{ "describe-I5", "" },
	{ "describe-L1", "" },
	{ "describe-L2", "" },
	{ "describe-LE1", "" },
	{ "describe-P1", "" },
	{ "describe-S1", "" },
	{ "describe-S2", "" },
	{ "describe-S3", "" },
	{ "describe-S4", "" },
	{ "describe-T1", "" },
	{ "describe-Y1", "" },
	{ "display-autoPan", N_("Move the Main canvas if you drag near the edge") },
	{ "display-carhotbarlabels", N_("How to group cars on the Train Hot Bar") },
	{ "display-centerdraw", N_("Show crosshair at center of curves") },
	{ "display-color-draw", N_("Color draw objects by layer or individually") },
	{ "display-color-track", N_("Color tracks by layer or individually") },
	{ "display-constrainmain", N_("Whether the Main Drawing Area shows as much of the room as possible") },
	{ "display-description-fontsize", N_("Font size for labels on layout") },
	{ "display-donthidecursor", N_("Don't hide system cursor when program cursors are showing") },
	{ "display-endpt", N_("Controls the drawing of End-Points") },
	{ "display-hideTrainsInTunnels", N_("Don't show trains in tunnels when tunnels are hidden") },
	{ "display-hotbarlabels", N_("Label elements on the Hot Bar") },
	{ "display-labelenable", N_("Enable labels for Turnouts, Flextrack Lengths and Elevations") },
	{ "display-labelscale", N_("When to label Turnout, Flextrack Lengths and Elevations") },
	{ "display-layoutlabels", N_("Label elements on layout") },
	{ "display-listlabels", N_("Label elements for lists") },
	{ "display-livemap", N_("Whether the main layout is updated while dragging on the Map") },
	{ "display-mapscale", N_("Drawing scale of the map window") },
	{ "display-ok", "" },
	{ "display-tiedraw", N_("How to draw track ties") },
	{ "display-trainpause", N_("Delay (in mS) between updating train movements") },
	{ "display-tunnels", N_("Controls the drawing of hidden tracks") },
	{ "display-tworailscale", N_("Drawing scale when to draw tracks with 2 rails") },
	{ "display-unconnected-endpt", N_("Display unconnected endpoints of track with special marks") },
	{ "draw-angle", N_("Angle of Line") },
	{ "draw-arrowsize", N_("Size of Dimension Arrows") },
	{ "draw-benchcolor", N_("Color of Benchwork") },
	{ "draw-benchlist", N_("List of types of Lumber") },
	{ "draw-benchorient", N_("Orientation of Benchwork") },
	{ "draw-height", N_("Height of Box") },
	{ "draw-linecolor", N_("Color of the lines") },
	{ "draw-linewidth", N_("Width of the lines") },
	{ "draw-radius", N_("Radius of Curve") },
	{ "draw-type", N_("Line Type") },
	{ "draw-width", N_("Width of Box") },
	{ "drawMod", N_("Modify Draw") },
	{ "drawMod-Angle", N_("Angle") },
	{ "drawMod-ArcAngle", N_("Arc Angle") },
	{ "drawMod-Height", N_("Height") },
	{ "drawMod-Length", N_("Length") },
	{ "drawMod-Radius", N_("Radius") },
	{ "drawMod-RelAngle", N_("Relative Angle") },
	{ "drawMod-RotAngle", N_("Rotation Angle") },
	{ "drawMod-RotCenterx", N_("Rot Center X") },
	{ "drawMod-RotCentery", N_("Rot Center Y") },
	{ "drawMod-Width", N_("Width") },
	{ "easement-l", N_("Easement length") },
	{ "easement-ok", N_("Complete easement selection") },
	{ "easement-r", N_("Minimum radius") },
	{ "easement-radio", N_("These radio buttons are a short-cut for Values of 0.0, 0.5, 1.0 and 2.0.  None turns Easements off") },
	{ "easement-val", N_("This controls the sharpness of the easement curve") },
	{ "easement-x", N_("Maximum offset") },
	{ "editM", N_("Edit menu") },
	{ "elev-computed", N_("Compute elevation based on neighbors") },
	{ "elev-grade", N_("Compute grade based on neighbors") },
	{ "elev-mode", N_("Type of elevation") },
	{ "elev-ok", "" },
	{ "elev-station", N_("Specify a name for an End-Point") },
	{ "elev-value", N_("Height of End Point") },
	{ "enum-list-indexes", N_("Enable index listing on the Parts List") },
	{ "enum-list-prices", N_("Enable prices on the Parts List") },
	{ "enum-print", N_("Print parts list") },
	{ "enum-printsetup", N_("Invoke the Print Setup dialog") },
	{ "enum-save", N_("Save parts list to file") },
	{ "enum-text", N_("This is the list of parts for the layout") },
	{ "fileNote-browse", N_("Select the file from your system") },
	{ "fileNote-filename", N_("Enter the path and name of the file") },
	{ "fileNote-layer", N_("Set the layer for the note") },
	{ "fileNote-ok", N_("Save the note and close window") },
	{ "fileNote-openfile", N_("Open the document in the default application") },
	{ "fileNote-origx", N_("Set the position for the note") },
	{ "fileNote-origy", N_("Set the position for the note") },
	{ "fileNote-title", N_("Enter the title of the file") },
	{ "fontSelCancel", N_("Cancel") },
	{ "fontSelList", N_("List") },
	{ "fontSelOk", N_("Ok") },
	{ "fontSelSample", N_("Sample") },
	{ "fontSelSize", N_("Size") },
	{ "fontSelSlant", N_("Slant") },
	{ "fontSelW", N_("Font selection dialog") },
	{ "fontSelWeight", N_("Weight") },
	{ "grid-horzdivision", N_("Allows the spacing to be subdivided") },
	{ "grid-horzenable", N_("Specifies if positions are snaped in this direction") },
	{ "grid-horzspacing", N_("Spacing between major grid lines") },
	{ "grid-ok", N_("Completes the grid specification") },
	{ "grid-origa", N_("Shows the origin and angle of the grid") },
	{ "grid-origx", N_("Shows the origin and angle of the grid") },
	{ "grid-origy", N_("Shows the origin and angle of the grid") },
	{ "grid-show", N_("Specifies if the grid is shown") },
	{ "grid-vertdivision", N_("Allows the spacing to be subdivided") },
	{ "grid-vertenable", N_("Specifies if positions are snaped in this direction") },
	{ "grid-vertspacing", N_("Spacing between major grid lines") },
	{ "group-desc", N_("Description") },
	{ "group-manuf", N_("Manufacturer") },
	{ "group-ok", N_("Creates a new Structure (or Turnout)") },
	{ "group-partno", N_("Part Number") },
	{ "group-replace", N_("Replace the Selected object with the new definition?") },
	{ "group-segcnt", N_("Number of segments in Group") },
	{ "helix-angSep", N_("Angle between helix entrance and exit") },
	{ "helix-elev", N_("Elevation difference of Helix End-Points") },
	{ "helix-grade", N_("Grade in helix") },
	{ "helix-radius", N_("Helix Radius") },
	{ "helix-turns", N_("Number of turns in the helix") },
	{ "helix-vertSep", N_("Separation between helix layers including baseboard, track, etc") },
	{ "hotBarLeft", N_("Move Hot Bar left") },
	{ "hotBarRight", N_("Move Hot Bar right") },
	{ "index-select", N_("Index numbers of objects, separated by commas") },
	{ "infoBarCount", N_("Total track count") },
	{ "infoBarPosX", N_("X Position of cursor") },
	{ "infoBarPosY", N_("Y Position of cursor") },
	{ "infoBarScale", N_("Drawing scale") },
	{ "infoBarStatus", N_("Message and status line") },
	{ "joinfixed-radius", N_("Desired curve radius between straight tracks") },
	{ "layer-add", N_("Add a new layer after the selected layer") },
	{ "layer-button", N_("Hide Layer Button on MenuBar") },
	{ "layer-button-count", N_("Number of layer buttons to show") },
	{ "layer-clear", N_("Overwrite layer configuration with system default values") },
	{ "layer-color", N_("Color of layer") },
	{ "layer-default", N_("Reset the layer to layout defaults") },
	{ "layer-delete", N_("Delete the selected layer. There must be no objects in it.") },
	{ "layer-frozen", N_("Layer cannot be changed") },
	{ "layer-gauge", N_("Specifies the rail gauge for this Layer") },
	{ "layer-inherit", N_("Layer inherits settings from Layout") },
	{ "layer-layer", N_("Layer list") },
	{ "layer-layercolor", N_("Use color for this Layer if color-by-layer is set") },
	{ "layer-layerlist", N_("Other Layers this Layer also shows/hides") },
	{ "layer-maxtrackgrade", N_("Specifies maximum track grade percent (%) for this layer. Tracks with a larger grade are considered exceptional.") },
	{ "layer-mintrackradius", N_("Specifies minimum track radius for this layer. Tracks with a smaller radius are considered exceptional.") },
	{ "layer-module", N_("Layer is a Module") },
	{ "layer-name", N_("Layer Name") },
	{ "layer-object-count", N_("Number of objects in this layer") },
	{ "layer-ok", "" },
	{ "layer-onmap", N_("Layer is drawn on Map window") },
	{ "layer-reset", N_("Load layer configuration from default") },
	{ "layer-save", N_("Save current layer configuration as default") },
	{ "layer-scale", N_("Specifies the Modelling Scale for this Layer") },
	{ "layer-settings", N_("Settings File to load when this layer is made current") },
	{ "layer-tielength", N_("Specifies the tie length for this layer.") },
	{ "layer-tiespacing", N_("Specifies the tie spacing for this layer.") },
	{ "layer-tiewidth", N_("Specifies the tie width for this layer.") },
	{ "layer-visible", N_("Layer is drawn on Main window") },
	{ "layout-backgroundAngle", N_("Specifies the rotation angle of the background image in degrees") },
	{ "layout-backgroundScreen", N_("Specifies the screening of the background image from 0 (none) to 100% (vanishes)") },
	{ "layout-backgroundWidth", N_("Specifies how large the bottom edge of the background image should be in model units") },
	{ "layout-backgroundposX", N_("Specifies the x offset of the bottom left of the background image") },
	{ "layout-backgroundposY", N_("Specifies the y offset of the bottom left of the background image") },
	{ "layout-browse", N_("Select the background image") },
	{ "layout-clear", N_("Remove the background image") },
	{ "layout-gauge", N_("Specifies the rail gauge, ie. the distance between the rails") },
	{ "layout-maxtrackgrade", N_("Specifies maximum track grade expressed as a percent (%). Tracks with a larger grade are considered exceptional.") },
	{ "layout-mintrackradius", N_("Specifies minimum track radius (in inches or centimeters). Tracks with a smaller radius are considered exceptional.") },
	{ "layout-read", N_("Override current settings from a named file") },
	{ "layout-roomsizeX", N_("Specifies the size of the room (in inches or centimeters)") },
	{ "layout-roomsizeY", N_("Specifies the size of the room (in inches or centimeters)") },
	{ "layout-scale", N_("Specifies the Modelling Scale") },
	{ "layout-tielength", N_("Specifies the tie length for the layout.") },
	{ "layout-tiespacing", N_("Specifies the tie spacing for the layout.") },
	{ "layout-tiewidth", N_("Specifies the tie width for the layout.") },
	{ "layout-title1", N_("Specifies the layout Title that will appear on printouts") },
	{ "layout-title2", N_("Specifies the layout Subtitle that will appear on printouts") },
	{ "layout-write", N_("Write a copy of current settings to a named file") },
	{ "linkNote-layer", N_("Set the layer for the note") },
	{ "linkNote-name", N_("Enter the URL for the webpage") },
	{ "linkNote-ok", N_("Save the link and close window") },
	{ "linkNote-openlink", N_("Open the webpage in your browser") },
	{ "linkNote-origx", N_("Set the position for the note") },
	{ "linkNote-origy", N_("Set the position for the note") },
	{ "linkNote-title", N_("Enter the title of the linked webpage") },
	{ "loosen", N_("No Help") },
	{ "main-canvas", N_("Main drawing canvas") },
	{ "main-commandbar", N_("Command buttons") },
	{ "main-draw", N_("Main layout canvas") },
	{ "main-hotbar", N_("Turnout and Structure Hot Bar") },
	{ "main-layers", N_("Active layer list and layer buttons") },
	{ "main-menubar", N_("Menus") },
	{ "main-titlebar", N_("Title, Filename and Window Manager buttons") },
	{ "mainDraw", N_("Main layout canvas") },
	{ "map-canvas", N_("No Help") },
	{ "map-draw", N_("Map window") },
	{ "map-hilight", N_("This is the portion of the layout shown in the Main Window canvas") },
	{ "menuEdit-redraw", N_("Redraw layout") },
	{ "menuEdit-zoomIn", N_("Zoom in") },
	{ "menuEdit-zoomOut", N_("Zoom out") },
	{ "menuFile", N_("File Menu") },
	{ "menuFile-clear", N_("New layout") },
	{ "menuFile-enum", N_("Generate parts list") },
	{ "menuFile-load", N_("Load a layout") },
	{ "menuFile-parameter", N_("Manage Parameter Files") },
	{ "menuFile-print", N_("Print layout") },
	{ "menuFile-quit", N_("Exit the program") },
	{ "menuFile-revert", N_("Revert to last saved state of layout plan") },
	{ "menuFile-save", N_("Save layout") },
	{ "menuFile-saveAs", N_("Save layout under a new name ") },
	{ "menuFile-setup", N_("Printer Setup") },
	{ "menuHelp", N_("Help menu") },
	{ "menuHelpProblemrep", N_("Create ZIP file with problem data") },
	{ "menuHelpRecentMessages", N_("Recent error messages and explanations") },
	{ "menuMacro", N_("Playback/Record commands") },
	{ "menuOption", N_("Options menu") },
	{ "menuToolbar", N_("Toolbar configuration") },
	{ "menuTools", N_("Tools menu") },
	{ "menuView", N_("View menu") },
	{ "menuWindow", N_("Window menu") },
	{ "misc-cur-turnout-ep", "" },
	{ "misc-group-objects", N_("No Help") },
	{ "misc-showabove", N_("No Help") },
	{ "misc-showaddElevations", N_("No Help") },
	{ "misc-showbelow", N_("No Help") },
	{ "misc-showcaradd", N_("No Help") },
	{ "misc-showcardesc", N_("No Help") },
	{ "misc-showclearElevations", N_("No Help") },
	{ "misc-showcmdopt", N_("No Help") },
	{ "misc-showcolor", N_("No Help") },
	{ "misc-showcopy", N_("No Help") },
	{ "misc-showcustomMgm", N_("No Help") },
	{ "misc-showcut", N_("No Help") },
	{ "misc-showdebug", N_("No Help") },
	{ "misc-showdelete", N_("No Help") },
	{ "misc-showdisplay", N_("No Help") },
	{ "misc-showeasement", N_("No Help") },
	{ "misc-showexport", N_("No Help") },
	{ "misc-showexportDXF", N_("No Help") },
	{ "misc-showfileClear", N_("No Help") },
	{ "misc-showfontSel", N_("No Help") },
	{ "misc-showgrid", N_("No Help") },
	{ "misc-showimport", N_("No Help") },
	{ "misc-showlayers", N_("No Help") },
	{ "misc-showlayout", N_("No Help") },
	{ "misc-showloosen", N_("No Help") },
	{ "misc-showmoveToCurrentLayer", N_("No Help") },
	{ "misc-shownotes", N_("No Help") },
	{ "misc-showparamFile", N_("No Help") },
	{ "misc-showpartsList", N_("No Help") },
	{ "misc-showpaste", N_("No Help") },
	{ "misc-showpref", N_("No Help") },
	{ "misc-showpriceList", N_("No Help") },
	{ "misc-showprint", N_("No Help") },
	{ "misc-showprintBitmap", N_("No Help") },
	{ "misc-showprintSetup", N_("No Help") },
	{ "misc-showrecompelev", N_("No Help") },
	{ "misc-showredo", N_("No Help") },
	{ "misc-showselectAll", N_("No Help") },
	{ "misc-showselectCurrentLayer", N_("No Help") },
	{ "misc-showtunnel", N_("No Help") },
	{ "misc-showundo", N_("No Help") },
	{ "misc-showwidth0", N_("No Help") },
	{ "misc-showwidth2", N_("No Help") },
	{ "misc-showwidth3", N_("No Help") },
	{ "misc-sticky", N_("No Help") },
	{ "misc-toolbarset", N_("No Help") },
	{ "misc-ungroup-objects", N_("No Help") },
	{ "move-MoveX", N_("Move by X") },
	{ "move-MoveY", N_("Move by Y") },
	{ "newcar-number", N_("Car Number") },
	{ "newcar-road", N_("Roadname") },
	{ "note-ok", "" },
	{ "note-text", N_("This is the body of the Note.  To change this select Modify from the File Menu") },
	{ "outputbitmap-density", N_("Specifies number of pixels per inch (or centimeter)") },
	{ "outputbitmap-ok", "" },
	{ "outputbitmap-toggles", N_("Specifies whether Layout Titles, Borders or Track Centerlines are printed on the BitMap") },
	{ "parallel-factor", N_("Specifies the a factor that increases the seperation as the radius of the original track reduces. 0.0 means no increase.") },
	{ "parallel-separation", N_("Specifies the separation between the original track and the parallel track/line") },
	{ "parameter-key", N_("Enter the key value as specified in the XTrackCAD Registration Notice") },
	{ "parameter-name", N_("Enter your name as specified in the XTrackCAD Registration Notice") },
	{ "parameter-ok", N_("Validates the name and key.  Terminates the registration command") },
	{ "pref-anglesystem", N_("0 degrees is up or to the right") },
	{ "pref-autosave", N_("Specifies the number of checkpoints after save before auto-saving.") },
	{ "pref-balloonhelp", N_("Enable/Disable balloon popup help windows") },
	{ "pref-checkpoint", N_("Specifies the Check Point frequency; number of modifications made since the last checkpoint.") },
	{ "pref-connectangle", N_("Minimum angle between connected End-Points") },
	{ "pref-connectdistance", N_("Maximum distance between connected end points") },
	{ "pref-coupling-speed-max", N_("Trains will crash above this speed") },
	{ "pref-dragpixels", N_("How far you can move the mouse before its considered a drag") },
	{ "pref-dragtimeout", N_("How long you can hold a mouse button down before its considered a drag") },
	{ "pref-dstfmt", N_("How to display length measurements") },
	{ "pref-mingridspacing", N_("Minimum distance (in pixels) between grid lines/ticks") },
	{ "pref-minlength", N_("Do not create tracks to be shorter than this value") },
	{ "pref-ok", "" },
	{ "pref-onstartup", N_("Resume work on last layout or start with new layout") },
	{ "pref-showflextrack", N_("Enable/Disable show of flextrack on hotbar") },
	{ "pref-turntable-angle", N_("Specifies the minimum angle between tracks connected to a turntable") },
	{ "pref-units", N_("Choose english (inches) or metric (centimeters)") },
	{ "pricelist-cost", N_("Updated cost of current selected item") },
	{ "pricelist-entry", N_("Item") },
	{ "pricelist-flexcost", N_("Price of specified length of flex-track") },
	{ "pricelist-flexlen", N_("Length of a piece of flex-track") },
	{ "pricelist-inx", N_("Selection list for prices") },
	{ "pricelist-ok", "" },
	{ "print-centerLine", N_("Controls the printing of a centerline of track cmdPrint") },
	{ "print-clear", N_("Deselects all pages") },
	{ "print-format", N_("Print page in Portrait or Landscape format") },
	{ "print-grid", N_("Print Snap Grid?") },
	{ "print-max", N_("Sets page size to the maximum (based on scale and physical page size)") },
	{ "print-ok", N_("Print selected pages and terminates the print command") },
	{ "print-order", N_("Order of printing pages") },
	{ "print-origa", N_("Origin of the print grid.  This is useful if you want to reprint a set of pages") },
	{ "print-origx", N_("Origin of the print grid.  This is useful if you want to reprint a set of pages") },
	{ "print-origy", N_("Origin of the print grid.  This is useful if you want to reprint a set of pages") },
	{ "print-pageh", N_("Scaled page height (Scale times physical page height)") },
	{ "print-pagew", N_("Scaled page width (Scale times physical page width)") },
	{ "print-physsize", N_("Ignore unprintable page margins?") },
	{ "print-registrationMarks", N_("Print Registration Marks at 1:1?") },
	{ "print-reset", N_("Resets the origin and angle to 0") },
	{ "print-roadbed", N_("Print Roadbed Outline?") },
	{ "print-roadbedWidth", N_("Print Roadbed Outline") },
	{ "print-ruler", N_("Print Rulers at the layout edge only, or on all page edges, or nowhere?") },
	{ "print-scale", N_("Controls the reduction (scale) of the printout") },
	{ "print-setup", N_("Invoke the Print Setup dialog") },
	{ "print-snapshot", N_("Sets scale, origin and angle for a one page printout of the layout") },
	{ "print-style", N_("Print Title, Date, Author and other information at bottom of page?") },
	{ "printAbortW", N_("Printer Abort Window") },
	{ "printFileName", N_("Print to filename") },
	{ "printFontAlias", N_("Specify Postscript font alias mapping") },
	{ "printSetup", N_("Displays the Print Setup window to change printers, orientation, paper size, etc.") },
	{ "printSetupCancel", N_("Closes this dialog") },
	{ "printSetupFormat", N_("Page orientation") },
	{ "printSetupMargin", N_("Unprintable margins") },
	{ "printSetupOk", N_("Updates and closes this dialog") },
	{ "printSetupPaper", N_("Choose paper size") },
	{ "printSetupPrinter", N_("Choose printer") },
	{ "printSetupTest", N_("Print test page") },
	{ "prmfile-action", N_("Toggle the shown status of the selected parameter file") },
	{ "prmfile-browse", N_("Find extra parameter files from the filesystem") },
	{ "prmfile-favorite", N_("Bookmark parameter files") },
	{ "prmfile-find", N_("Find parameter files from the system library") },
	{ "prmfile-inx", N_("List of loaded, shown or hidden parameter files") },
	{ "prmfile-mode", N_("Show parameter files by names or descriptions") },
	{ "prmfile-ok", N_("Update parameter file list") },
	{ "prmfile-refresh", N_("Reload parameter file from list") },
	{ "prmfile-selectall", N_("Select all parameter files shown") },
	{ "prmfile-unload", N_("Remove parameter files from active list") },
	{ "profile-canvas", N_("Profile of specified path") },
	{ "profile-clear", N_("Clear the profile") },
	{ "profile-ok", "" },
	{ "profile-print", N_("Print the profile") },
	{ "record-end", N_("End a message") },
	{ "record-message", N_("Insert a message") },
	{ "record-stop", N_("Stop recording") },
	{ "record-text", N_("Message body") },
	{ "refreshSpecial-list", N_("Possible turnouts") },
	{ "refreshSpecial-ok", "" },
	{ "refreshSpecial-skip", N_("Skip this turnout") },
	{ "rename-desc", N_("Description of Object") },
	{ "rename-manuf", N_("Manufacturer of Object") },
	{ "rename-ok", "" },
	{ "rename-partno", N_("Part Nuber of Object") },
	{ "rescale-change-dim", N_("Change track dimensions to new scale") },
	{ "rescale-fromG", N_("Original Gauge of the selected objects") },
	{ "rescale-fromS", N_("Original Scale of the selected objects") },
	{ "rescale-ok", "" },
	{ "rescale-ratio", N_("Change size by this amount") },
	{ "rescale-toG", N_("New Gauge of the selected objects") },
	{ "rescale-toS", N_("New Scale of the selected objects") },
	{ "rescale-toggle", N_("Rescale by Scale Conversion or by Ratio") },
	{ "rgbcolor-border", N_("Border rulers, room boundaries and table edges") },
	{ "rgbcolor-crossmajor", N_("Primary Axis of grid rotation") },
	{ "rgbcolor-crossminor", N_("Secondary Axis of grid rotation") },
	{ "rgbcolor-exception", N_("Color of Exceptional tracks") },
	{ "rgbcolor-marker", N_("X and Y position markers") },
	{ "rgbcolor-normal", N_("Unselected tracks") },
	{ "rgbcolor-ok", N_("Updates the colors") },
	{ "rgbcolor-profile", N_("Color of tracks on the Profile path") },
	{ "rgbcolor-selected", N_("Selected tracks") },
	{ "rgbcolor-snapgrid", N_("Snap Grid Line and Division") },
	{ "rgbcolor-tie", N_("Color of track ties") },
	{ "rotate-ok", N_("Rotate object(s) by specified amount") },
	{ "rotate-rotate", N_("Angle in degrees") },
	{ "searchgui-apply", N_("Add selected entries into parameter file list") },
	{ "searchgui-clearfilter", N_("Remove the current filter and show all files") },
	{ "searchgui-default", N_("Reload the system library contents for finding") },
	{ "searchgui-find", N_("Find matching file descriptions") },
	{ "searchgui-fit", N_("Select how well the definitions must fit the current layout scale") },
	{ "searchgui-inx", N_("Search results") },
	{ "searchgui-mode", N_("Show descriptions or filenames in results") },
	{ "searchgui-query", N_("Enter one or more words as search terms") },
	{ "searchgui-selectall", N_("Select All found entries") },
	{ "sticky-ok", N_("Make the commands sticky") },
	{ "sticky-set", N_("Choose commands to be sticky") },
	{ "structure-canvas", N_("Diagram of the selected structure") },
	{ "structure-hide", N_("Hide Selection window when placing Structure") },
	{ "structure-list", N_("List of available structure") },
	{ "structure-ok", N_("Complete structure placement") },
	{ "structure-pier-inx", N_("Choose a Pier number") },
	{ "structure-stats", N_("Drawing scale and size") },
	{ "switchmotor-name", N_("Name of the Motor") },
	{ "switchmotor-normal", N_("Value when switch is normal") },
	{ "switchmotor-pointSense", N_("Value for a positive comfirmation of switch position") },
	{ "switchmotor-reverse", N_("Value when the switch is reversed") },
	{ "text-boxed", N_("If the text is boxed") },
	{ "text-color", N_("Controls the color of the entered text") },
	{ "text-fontsize", N_("Controls the size of the entered text") },
	{ "textNote-layer", N_("Set layer for the note") },
	{ "textNote-ok", N_("Save and close editor dialog") },
	{ "textNote-origx", N_("Set the position for the note") },
	{ "textNote-origy", N_("Set the position for the note") },
	{ "textNote-text", N_("Enter your additional information here") },
	{ "tip-next", N_("Show the next Tip of the Day") },
	{ "tip-ok", "" },
	{ "tip-prev", N_("Show the previous Tip of the Day") },
	{ "tip-showatstart", N_("Show Tip of the Day every time the program starts") },
	{ "tip-text", N_("Useful information about the program") },
	{ "toolbar-invert", N_("Invert the visibility of button groups") },
	{ "toolbar-ok", N_("Close dialog and configure the toolbar") },
	{ "toolbar-selectall", N_("Set all button groups visible in toolbar") },
	{ "toolbar-toolbarset", N_("List of button groups and their state in the toolbar") },
	{ "toolsM", N_("Tools menu") },
	{ "train-autoreverse", N_("Flip direction at End Of Track") },
	{ "train-direction", N_("Change direction of train") },
	{ "train-distance", N_("Train odometer") },
	{ "train-follow", N_("Follow train around layout") },
	{ "train-goto", N_("Find train on layout") },
	{ "train-list", N_("List of active trains") },
	{ "train-newcar-index", N_("List of Cars") },
	{ "train-speed", N_("Speed") },
	{ "train-stop", N_("Stop the train") },
	{ "train-zeroDistance", N_("Reset odometer to 0") },
	{ "turnout-activeEndPoint", N_("The selected Active End-Point") },
	{ "turnout-canvas", N_("Diagram of the currently selected turnout.  Click on a End-Point to select the Active End-Point") },
	{ "turnout-current", N_("Current selected turnout, (displayed in the diagram window)") },
	{ "turnout-endPoint", N_("One the End-Points that can be selected") },
	{ "turnout-hide", N_("Hide Selection window when placing Turnout") },
	{ "turnout-list", N_("List of available turnouts for the current scale") },
	{ "turnout-new", N_("A menu list of various type of turnouts and sectional tracks you can define") },
	{ "turnout-ok", "" },
	{ "turnoutNew-angle1", N_("Angle of the specified track to the center line of the turnout") },
	{ "turnoutNew-angle2", N_("Angle of the specified track to the center line of the turnout") },
	{ "turnoutNew-angleMode", N_("Specifies if angles are entered as Frog Numbers or in degrees") },
	{ "turnoutNew-color", N_("Color of Roadbed lines") },
	{ "turnoutNew-desc1", N_("Description") },
	{ "turnoutNew-desc2", N_("Description") },
	{ "turnoutNew-done", N_("Closes the window and returns to the Turnout Selection window") },
	{ "turnoutNew-label", N_("Turnout description (Manuf., Size, Part Number, etc)") },
	{ "turnoutNew-len0", N_("Length from the base to the end of the specified track") },
	{ "turnoutNew-len1", N_("Length from the base to the end of the specified track") },
	{ "turnoutNew-len2", N_("Length from the base to the end of the specified track") },
	{ "turnoutNew-manuf", N_("Manufacturer") },
	{ "turnoutNew-off1", N_("Offset of the track End-Point from the center line of the turnout") },
	{ "turnoutNew-off2", N_("Offset of the track End-Point from the center line of the turnout") },
	{ "turnoutNew-ok", N_("Prints a full size diagram of the turnout for checking") },
	{ "turnoutNew-partno1", N_("Part Number") },
	{ "turnoutNew-partno2", N_("Part Number") },
	{ "turnoutNew-print", N_("Prints a full size diagram of the turnout for checking") },
	{ "turnoutNew-printsetup", N_("Invoke the Print Setup dialog") },
	{ "turnoutNew-roadbedLineWidth", N_("Width of Roadbed lines") },
	{ "turnoutNew-roadbedWidth", N_("Width of Roadbed") },
	{ "turntable-diameter", N_("Specifies the diameter of the turntable") },
	{ "updatetitle-ignore", N_("Leave the Turnouts' title unchanged") },
	{ "updatetitle-list", N_("List of available turnouts") },
	{ "updatetitle-load", N_("Invoke the Parameter Files dialog") },
	{ "updatetitle-ok", N_("Update the Turnouts' title") },
	{ "updatetitle-old", N_("Old Turnout title") },
	{ "updatetitle-sel", N_("List of available titles") },
	{ NULL, NULL } };
