#!/usr/bin/env bash

if [ "$1" = "-h" ]; then
	echo "$0"
	echo "Create source tar ball in build directory"
	echo "Run from <SRCDIR>/distribution/flatpak"
	echo "Computes sha256 checksum which must be updated in manifest file"
	exit 0
fi

SRCDIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
cd -- "$SRCDIR"
BLDDIR=build

cd ../..

BUILD_TYPE="-DCMAKE_BUILD_TYPE=Debug"
if command -v ninja >/dev/null 2>&1 && [ ! -s Makefile ]; then
	cmake $BUILD_TYPE -DXTRKCAD_BUILD_FLATPAK=1 -G Ninja -B $BLDDIR -S .
else
	cmake $BUILD_TYPE -DXTRKCAD_BUILD_FLATPAK=1 -B $BLDDIR -S .
fi
hg revert -C app/lib/xtrkcad.metainfo.xml 2>/dev/null
hg revert -C app/lib/xtrkcad.flatpak.desktop 2>/dev/null

TODAY=$(date --utc '+%Z %Y-%m-%d %H:00')
TAROPTS='--sort=name --mtime="$TODAY" --owner=0 --group=0 --numeric-owner --format=gnu'
if [ -f $HOME/.tarignore ]; then
	# get list of excludes from a file
	eval tar cf ${BLDDIR}/source.tar $TAROPTS --exclude-from=$HOME/.tarignore .
else
	eval tar cf ${BLDDIR}/source.tar $TAROPTS --exclude-vcs --exclude=$BLDDIR --exclude-vcs-ignores .
fi

cd $BLDDIR
rm -f source.tar.gz
# -n zeros the timestamp so repeated runs yield the same checksum
gzip -n source.tar
echo "Update manifest.yaml with this sha256 checksum here and in git repo (tbd)"
# rename by version
if [ -f xtrkcad-config.h ]; then
	VERSION=$(grep "#define XTRKCAD_VERSION " xtrkcad-config.h | cut -d" " -f3 | tr -d '"')
	mv source.tar.gz source-${VERSION}.tar.gz
	sha256sum source-${VERSION}.tar.gz
else
	echo "$BLDDIR/xtrkcad-config.h not found, so cannot get version"
	sha256sum source.tar.gz
fi
