#!/usr/bin/env bash

if [ $# -ne 1 ]; then
	echo "$0 <BLDDIR>"
	echo "Create source tar ball"
	echo "Run from <SRCDIR>/distribution/flatpak"
	echo "Computes sha256 checksum which must be updated in manifest file"
	exit 0
fi

SRCDIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
cd -- "$SRCDIR"
BLDDIR=$1

cd ../..
if [ -f $HOME/.tarignore ]; then
	# get list of excludes from a file
	tar cf ${BLDDIR}/source.tar --exclude-from=$HOME/.tarignore .
else
	tar cf ${BLDDIR}/source.tar --exclude-vcs --exclude=build --exclude-vcs-ignores .
fi
# current flatpak builds everything, so these additions not necessary
#cd $BLDDIR/../../app/bin
#tar rf ${BLDDIR}/source.tar ./bitmaps

cd $BLDDIR
rm -f source.tar.gz
# -n zeros the timestamp so repeated runs yield the same checksum
gzip -n source.tar
echo "Update manifest.yaml with this sha256 checksum here and in git repo (tbd)"
# rename by version
if [ -f xtrkcad-config.h ]; then
	VERSION=$(grep "#define XTRKCAD_VERSION " xtrkcad-config.h | cut -d" " -f3 | tr -d '"')
	mv source.tar.gz source-${VERSION}.tar.gz
	sha256sum source-${VERSION}.tar.gz
else
	echo "$BLDDIR/xtrkcad-config.h not found, so cannot get version"
	sha256sum source.tar.gz
fi
