#!/bin/bash
if [ $# -ne 1 ] ; then
	echo "$0 <BLDDIR>/distribution/flatpak"
	echo "Create source tar ball, with .xpm3 files"
	echo "Run from <SRCDIR>/distribution/flatpak"
	echo "Computes sha256 checksum which must be updated in manifest file"
	exit 0
fi

SRCDIR=`pwd`
BLDDIR=$1

cd ../..
if [ -f $HOME/.tarignore ]; then
    # get list of excludes from a file
    tar cf ${BLDDIR}/source.tar --exclude-from=$HOME/.tarignore .
else
    tar cf ${BLDDIR}/source.tar --exclude-vcs --exclude=build --exclude-vcs-ignores .
fi
# current flatpak builds everything, so these additions not necessary
#cd $BLDDIR/../../app/bin
#tar rf ${BLDDIR}/source.tar ./bitmaps

cd $BLDDIR
rm -f source.tar.gz
# -n zeros the timestamp so repeated runs yield the same checksum
gzip -n source.tar
echo "Update manifest.yaml with this sha256 checksum here and in git repo (tbd)"
sha256sum source.tar.gz
